<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Fulbii reúne canchas, pichangas, grupos, retos y tu perfil futbolero en una sola app.">
  <title>Fulbii · Tu próxima pichanga empieza aquí</title>
  <style>
    :root { --ink:#0a1510; --surface:#f8fbf7; --green:#23623a; --mint:#aadca0; --line:#d5e2d2; --muted:#526158; --orange:#df7e37; }
    * { box-sizing:border-box; } body { margin:0; color:var(--ink); background:var(--surface); font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
    a { color:inherit; text-decoration:none; } .shell { width:min(1140px,calc(100% - 40px)); margin:auto; } .nav { display:flex; align-items:center; justify-content:space-between; gap:20px; padding:20px 0; } .brand { display:flex; align-items:center; font-weight:850; letter-spacing:-.05em; font-size:1.45rem; } .brand i { display:grid; place-items:center; width:34px; height:34px; margin-right:9px; border-radius:11px; background:var(--green); color:#fff; font-style:normal; } .nav-links { display:flex; gap:20px; color:var(--muted); font-size:.94rem; } .hero { overflow:hidden; padding:54px 0 68px; background:linear-gradient(118deg,#edf7ea 0%,#d7ebcf 48%,#b6d9ac 100%); border-bottom:1px solid var(--line); } .hero-grid { display:grid; grid-template-columns:1.05fr .95fr; align-items:center; gap:42px; } .eyebrow { margin:0 0 14px; color:var(--green); font-weight:800; letter-spacing:.1em; text-transform:uppercase; font-size:.76rem; } h1 { max-width:720px; margin:0; font-size:clamp(2.55rem,6vw,5.5rem); letter-spacing:-.075em; line-height:.94; } .hero p { max-width:600px; margin:24px 0 0; color:#314036; font-size:1.12rem; line-height:1.6; } .actions { display:flex; flex-wrap:wrap; gap:12px; margin-top:30px; } .button { display:inline-flex; align-items:center; justify-content:center; min-height:48px; border-radius:999px; padding:0 21px; background:var(--green); color:#fff; font-weight:760; } .button.secondary { border:1px solid #8aa282; background:#fff; color:var(--green); } .button.disabled { background:#e5ece2; color:#657168; cursor:default; } .phone { position:relative; min-height:410px; border:12px solid #0f1d14; border-radius:42px; background:#0f2115 url('{{ asset('assets/images/landing-banner.png') }}') center/cover; box-shadow:0 24px 56px rgba(21,61,30,.25); transform:rotate(4deg); } .phone:before { content:""; position:absolute; top:15px; left:50%; width:42%; height:24px; transform:translateX(-50%); border-radius:999px; background:#0b140e; } .phone-copy { position:absolute; left:22px; right:22px; bottom:22px; padding:20px; border:1px solid rgba(255,255,255,.42); border-radius:22px; background:rgba(12,31,19,.86); color:#fff; backdrop-filter:blur(7px); } .phone-copy strong { display:block; font-size:1.3rem; } .phone-copy span { display:block; margin-top:7px; color:#d8ecd2; line-height:1.35; }
    section { padding:78px 0; } h2 { margin:0; max-width:720px; font-size:clamp(2rem,4vw,3.2rem); letter-spacing:-.055em; line-height:1; } .section-copy { max-width:650px; margin:17px 0 0; color:var(--muted); line-height:1.6; } .grid { display:grid; grid-template-columns:repeat(3,1fr); gap:16px; margin-top:34px; } .card { min-height:190px; padding:25px; border:1px solid var(--line); border-radius:24px; background:#fff; box-shadow:0 14px 28px rgba(22,47,28,.045); } .card-icon { display:grid; place-items:center; width:42px; height:42px; border-radius:14px; background:#e6f2e2; color:var(--green); font-size:1.35rem; } .card h3 { margin:18px 0 8px; font-size:1.17rem; } .card p { margin:0; color:var(--muted); line-height:1.5; font-size:.96rem; } .band { background:#102317; color:#eff7ec; } .band .section-copy { color:#b9cdb8; } .steps { display:grid; grid-template-columns:repeat(3,1fr); gap:14px; margin-top:36px; } .step { padding:23px; border:1px solid #34513b; border-radius:21px; } .step b { display:block; color:var(--mint); font-size:.79rem; letter-spacing:.08em; text-transform:uppercase; } .step strong { display:block; margin-top:12px; font-size:1.16rem; } .step span { display:block; margin-top:8px; color:#c5d8c3; line-height:1.5; font-size:.94rem; } .cta { text-align:center; padding:84px 0; } .cta p { margin:18px auto 0; max-width:560px; color:var(--muted); line-height:1.6; } footer { padding:28px 0; border-top:1px solid var(--line); color:var(--muted); font-size:.9rem; } footer .shell { display:flex; justify-content:space-between; gap:18px; flex-wrap:wrap; }
    @media (max-width:760px) { .shell { width:min(100% - 28px,620px); }.nav-links { display:none; }.hero { padding:28px 0 45px; }.hero-grid { grid-template-columns:1fr; }.phone { min-height:310px; margin:12px 18px 0; transform:rotate(2deg); }.grid,.steps { grid-template-columns:1fr; } section { padding:58px 0; } }
  </style>
</head>
<body>
    <header class="shell nav">
    <a class="brand" href="{{ url('/') }}"><i>⚽</i>Fulbii</a>
    <nav class="nav-links" aria-label="Navegación principal"><a href="#como-funciona">Cómo funciona</a><a href="#funciones">Funciones</a><a href="#descargar">Descargar</a><a href="{{ route('support') }}">Soporte</a><a href="{{ route('privacy') }}">Privacidad</a><a href="{{ $supportWhatsappUrl }}" target="_blank" rel="noopener">WhatsApp</a><a href="{{ route('login') }}">Administración</a></nav>
  </header>
  <main>
    <section class="hero"><div class="shell hero-grid"><div><p class="eyebrow">La comunidad de tu próxima pichanga</p><h1>Juega más.<br>Coordina mejor.</h1><p>Encuentra canchas, organiza pichangas, reúne a tu grupo, compite en retos y construye tu perfil futbolero desde una sola app.</p><div class="actions"><a class="button" href="fulbii://pichangas">Abrir Fulbii</a>@if($iosStoreUrl !== '')<a class="button secondary" href="{{ $iosStoreUrl }}">Descargar en iPhone</a>@endif @if($androidStoreUrl !== '')<a class="button secondary" href="{{ $androidStoreUrl }}">Descargar en Android</a>@endif</div></div><div class="phone" aria-label="Vista previa de Fulbii"><div class="phone-copy"><strong>Todo el fútbol de tu barrio</strong><span>Canchas, cupos, grupos y tu próxima jugada.</span></div></div></div></section>
    <section id="funciones"><div class="shell"><p class="eyebrow">Una app, una comunidad</p><h2>Desde encontrar cancha hasta recordar el partido.</h2><p class="section-copy">Fulbii concentra los momentos que normalmente terminan repartidos entre chats, listas y llamadas.</p><div class="grid"><article class="card"><div class="card-icon">⌖</div><h3>Canchas cerca de ti</h3><p>Explora recintos, compara formatos, superficies, precios y pichangas abiertas en el mapa.</p></article><article class="card"><div class="card-icon">⚽</div><h3>Pichangas sin caos</h3><p>Crea, confirma, entra a lista de espera y coordina equipos, cancha y horario con claridad.</p></article><article class="card"><div class="card-icon">♟</div><h3>Grupos que se mueven</h3><p>Organiza comunidades, asigna administradores, conversa y elige cómo se crean sus pichangas.</p></article><article class="card"><div class="card-icon">↗</div><h3>Retos entre grupos</h3><p>Propón cancha y fecha, conversa en contexto y lleva la coordinación del reto en un solo lugar.</p></article><article class="card"><div class="card-icon">★</div><h3>Perfil y ranking</h3><p>Recibe calificaciones responsables, conoce tu posición sugerida y compite en rankings globales y por edad.</p></article><article class="card"><div class="card-icon">⌚</div><h3>Tu partido, con contexto</h3><p>Conecta sesiones Watch, actividad, feed y recuerdos de cada pichanga sin perder el hilo.</p></article></div></div></section>
    <section class="band" id="como-funciona"><div class="shell"><p class="eyebrow" style="color:#aadca0">Diseñado para la cancha</p><h2>Organiza en minutos. Juega con confianza.</h2><p class="section-copy">Las notificaciones, permisos y estados de asistencia evitan la incertidumbre antes de salir a jugar.</p><div class="steps"><article class="step"><b>01 · Descubre</b><strong>Encuentra una cancha o una pichanga abierta.</strong><span>Filtra por horario, formato, superficie, precio y disponibilidad.</span></article><article class="step"><b>02 · Coordina</b><strong>Confirma, conversa y define tu equipo.</strong><span>Grupos, retos, lista de espera y chats mantienen a todos informados.</span></article><article class="step"><b>03 · Evoluciona</b><strong>Juega, califica y sigue mejorando.</strong><span>Tu historial, rankings y actividad hacen visible cada partido.</span></article></div></div></section>
    <section><div class="shell"><p class="eyebrow">Comunidad cuidada</p><h2>Más juego, menos fricción.</h2><div class="grid"><article class="card"><div class="card-icon">✓</div><h3>Asistencia clara</h3><p>Confirmaciones, cupos, lista de espera y recordatorios para que nadie quede sin saber qué pasa.</p></article><article class="card"><div class="card-icon">♧</div><h3>Control para cada grupo</h3><p>Administradores, invitaciones, preferencias de notificaciones y reportes para una comunidad sana.</p></article><article class="card"><div class="card-icon">◌</div><h3>Notificaciones útiles</h3><p>Actualizaciones importantes, chat y decisiones se enlazan directamente con el contenido correcto.</p></article></div></div></section>
    <section id="descargar" class="cta"><div class="shell"><p class="eyebrow">Tu próxima pichanga</p><h2>Empieza desde Fulbii.</h2><p>Abre la app para descubrir dónde jugar, organizar a tu grupo y llegar a la cancha con todo resuelto.</p><div class="actions" style="justify-content:center"><a class="button" href="fulbii://pichangas">Abrir Fulbii</a>@if($iosStoreUrl !== '')<a class="button secondary" href="{{ $iosStoreUrl }}">iPhone</a>@endif @if($androidStoreUrl !== '')<a class="button secondary" href="{{ $androidStoreUrl }}">Android</a>@endif</div></div></section>
  </main>
  <footer><div class="shell"><span>© {{ now()->year }} Fulbii. Fútbol organizado, comunidad activa.</span><span><a href="{{ route('support') }}">Soporte</a> · <a href="{{ route('privacy') }}">Privacidad</a> · <a href="{{ $supportWhatsappUrl }}" target="_blank" rel="noopener">WhatsApp</a> · <a href="{{ route('login') }}">Administración</a></span></div></footer>
</body>
</html>
