[program:fulbii-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/fulbii/artisan queue:work --queue=default,push --tries=3 --backoff=30,120,300 --sleep=1 --timeout=120
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/fulbii-worker.log
stopwaitsecs=3600
